# -*- coding: utf-8 -*-
"""Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137fEbV55jwGTfH1hMBbzIsITbm1a6wZB
"""

# List operations
list = [10, 20, 30, 40]
print("Original List:", list)

# Addition of element
list.append(50)
print("List after adding:", list)

# Removing an element
list.remove(20)
print("List after removing an element:", list)

# Modify an element in the list
list[1] = 35
print("List after modifying:", list)


# Dictionary operations
dict = {'x': 10, 'y': 20, 'z': 30}
print("\nOriginal Dictionary:", dict)

# Add a key-value pair
dict['k'] = 40
print("Dictionary after adding a key-value pair:", dict)

# Remove a key-value pair
del dict['z']
print("Dictionary after removing a key-value pair:", dict)

# Modify a value
dict['y'] = 100
print("Dictionary after modifying a value:", dict)


# Set operations
set = {1, 2, 3}
print("\nOriginal Set:", set)

# Adding an element
set.add(4)
print("Set after adding :", set)

# Removing an element
set.discard(200)
print("Set after removing :", set)

# No modification for sets, so elements first removed and then add new ones.
set.discard(2)
set.add(15)
print("Set after modification:", set)

